name: Build & Tag Docker Image

on:
   push:
      branches: ["main"]
   pull_request:
      branches: ["main"]

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v4

         - name: Set timestamp
           id: vars
           run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

         - name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

         - name: Build the Docker image
           run: docker build . --file Dockerfile --tag subly:${{ steps.vars.outputs.timestamp }}

         - name: Push to Docker Hub
           run: |
              docker tag subly:${{ steps.vars.outputs.timestamp }} ${{ secrets.DOCKER_USERNAME }}/subly:latest
              docker push ${{ secrets.DOCKER_USERNAME }}/subly:latest
